-- dependency of fields in jobs
SELECT DISTINCT TABLE_NAME 
FROM SRG_DEV_RPT.INFORMATION_SCHEMA."COLUMNS" 
WHERE (COLUMN_NAME LIKE '%CHANNELCODE%' OR COLUMN_NAME LIKE '%CHANNEL_FK%')
--AND TABLE_SCHEMA IN ('REPORTING', 'STG');